#pragma once
#pragma once
#include "defines.h"
void check_formation(TEAM *team);
void graph_loading(void);
void change_feature(TEAM *a, TEAM *b);
void loading(char sit);
void SetColor(int ForgC);
void find_goaler(PLAYER *goaler, TEAM *team);
void reservedplayers_form(TEAM *team1, TEAM *team2);
void goal_process(TEAM *team1, TEAM *team2);
void set_team_id(TEAM *team);
int host_process(TEAM *host, TEAM *guest);
int guest_process(TEAM *host, TEAM *guest);
void play_game(TEAM *host, TEAM *guest);
void print_sched(TEAM *team, WEEK *gamesweek);
void nextgames(TEAM *team, WEEK *gamesweek);
void print(char str[50]);
void delay(float secs);
TEAM *newleague(TEAM *team);
void print_teams(TEAM *team);
void scoreboard(TEAM *team, TEAM *userteam);
void swap(TEAM *a, TEAM *b);
void formation(int a, int c, int b, TEAM *team);
void position(int n, TEAM *team, char pos);
PLAYER *find_bestplayer(TEAM *team, char pos, int zakhire);
PLAYER *find_wrostplayer(TEAM *team, char pos, int zakhire);
void change(PLAYER *player1, PLAYER *player2, int def);
void set_skill(TEAM *team);
void set_fitness(TEAM *team);
void team_info(TEAM *team);
TEAM *search_team_by_id(TEAM *team, int id);
void teams_formation(TEAM *team);
void taviz(int id1, int id2, TEAM *team);
void check_skill(PLAYER *player);
void set_other_skill(PLAYER *player);
void simulation(WEEK *gamesweek, TEAM *team, TEAM *userteam, int n);
void set_team_power(TEAM *team, TEAM *userteam);
void lineup(TEAM *userteam);
void weekly_games(WEEK *gamesweek, TEAM *team, TEAM *userteam);
void match_process(WEEK *gamesweek, TEAM *team, TEAM *userteam, int n);